networks:
  reserve-utsa:
    driver: bridge

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - ../.env
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ../nginx/cert/:/etc/nginx/cert/
    restart: always
    networks:
      - reserve-utsa