networks:
  reserve-utsa:
    driver: bridge

services:
  mongo-db: 
    image: mongo:latest
    container_name: mongo-db
    restart: always
    volumes: 
      - ../mongodb/configdb:/data/configdb
      - ../mongodb/data:/data/db
      - ../mongodb/mongod.conf:/etc/mongo/mongod.conf
    expose:
      - 27017
    networks:
      - reserve-utsa
    user: "1000:1000"