version: "3.9"

networks:
  reserve-utsa:
    driver: bridge

services:
  web:
    image: ghcr.io/utaipei-sa/reserve.utsa:${FRONTEND_VERSION}
    restart: always
    container_name: ui
    expose:
      - 80
    networks:
      - reserve-utsa